### ISSUE TITLE
Should execute return XML string?

### ISSUE THREAD

**Issue by sashman** [UP-nxt/cmis-ruby#19]
Hello I am making a connection with my server and trying to get back a list of repositories. Getting this error:
```
NoMethodError: undefined method `values' for #<String:0x5490bd0>
```

Looking into `server.rb` code there is this:
```
    def repositories(opts = {})
      result = execute!({}, opts)

      result.values.map do |r|
        Repository.new(r, self)
      end
    end
```
`execute` just returns the response body? Should this not get parsed somewhere? Or am I using this in a wrong way?

**Comment by kennethgeerts** [comment]
Thanks for the report. I'll look into it.
Can you paste a full trace of the error? And the piece of calling code that produces it.
For context, what CMIS server are you running against?

**Comment by sashman** [comment]
This is all I'm getting:
```
CMIS::Server[http://localhost:8080/alfresco/api/-default-/public/cmis/versions/1.0/atom]
rake aborted!
NoMethodError: undefined method `values' for #<String:0x6526cb0>
....rake:45:in `block (2 levels) in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'
Tasks: TOP => alfresco:read_folders
(See full trace by running task with --trace)
```

Here is my task:
```ruby
    server = CMIS::Server.new(service_url: 'http://localhost:8080/alfresco/api/-default-/public/cmis/versions/1.0/atom', username: 'admin', password: 'password')
    puts server.inspect
    puts server.repositories.inspect
```

Could this be due to me using an atom API?

**Comment by kennethgeerts** [comment]
> Could this be due to me using an atom API?

Yep. cmis-ruby talks to the browser binding only. I'll try to improve the error message though. Thanks!

**Comment by sashman** [comment]
Awesome cheers!

For the record I should have used this browser end point `http://localhost:8080/alfresco/cmisbrowser`

**Comment by kylefernandadams** [comment]
@sashman One point of clarification. If you're using Alfresco 5.x, the correct browser binding uri is the following:
http://localhost:8080/alfresco/api/-default-/public/cmis/versions/1.1/browser

**Comment by sashman** [comment]
thanks @kylefernandadams!
